version: '2'
services:
  cache:
    image: memcached:1.4.31-alpine
    ports:
      - "11211:11211"
  overlord:
    build: .
    ports:
      - "8089:8089"
    volumes:
      - ".:/srv/app"
    command: "locust -f /srv/app/locustfile.py --master --master-bind-port=5557 --host cache"
  minion:
    depends_on: overlord
    build: .
    volumes:
      - ".:/srv/app"
    command: "locust -f /srv/app/locustfile.py --slave --master-host=overlord --master-port=5557"

